### ISSUE TITLE
title of http://sweetontology.net/phenAtmoFront ontology

### ISSUE THREAD

**Issue by graybeal** [ESIPFed/sweet#143] opened 2019-07-18 21:56 UTC
Title of http://sweetontology.net/phenAtmoFront seems to have a mis-spelling, "SWEET Ontology Phenomena Atmosphoere Front" should be "SWEET Ontology Phenomena Atmosphere Front" (?)

**Comment by lewismc** [comment] 2019-07-19 03:47
Duplicate of #145

**Closed by lewismc** 2019-07-19 03:47 UTC
